### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by OrkoHunter** [OrkoHunter/networkx#2]
After forking the metis branch of www.github.com/ysitu/networkx, and importing the networkx, it gives some import errors

```
>>> import networkx
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "networkx/__init__.py", line 84, in <module>
  import networkx.generators
File "networkx/generators/__init__.py", line 5, in <module>
  from networkx.generators.classic import *
File "networkx/generators/classic.py", line 20, in <module>
  from networkx.algorithms.bipartite.generators import complete_bipartite_graph
File "networkx/algorithms/__init__.py", line 36, in <module>
  from networkx.algorithms.partition import *
File "networkx/algorithms/partition/__init__.py", line 1, in <module>
  from .metis import *
File "networkx/algorithms/partition/metis.py", line 17, in <module>
  from networkx.external.metis import *
File "networkx/external/metis/__init__.py", line 1, in <module>
  from .enums import *
File "networkx/external/metis/enums.py", line 1, in <module>
  from enum import IntEnum, unique
ImportError: No module named enum
```

**Comment by OrkoHunter** [comment]
enum34 was needed.
